name: luna_chess
description: A chess app with an AI companion named Luna.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  in_app_purchase: ^3.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_tts: ^3.8.5
  chess: ^0.8.1
  stockfish_flutter_plus: ^1.0.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
